"""
TalentLens configuration — paths, model settings, and UI constants.
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Paths (relative to the *project root*, i.e. TalentLens_Public/)
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
DS3_DIR = DATA_DIR / "ds3"
MEMBERS_CSV = DS3_DIR / "member_resumes" / "members.csv"
MEMBER_RESUMES_DIR = DS3_DIR / "member_resumes"
BOARD_RESUMES_TXT = DS3_DIR / "board_resumes" / "board.txt"

# Pipeline output artifacts (generated by pipeline/03_faiss_indexing.ipynb)
FAISS_INDEX_PATH = PROJECT_ROOT / "resume_index.faiss"
METADATA_PATH = PROJECT_ROOT / "member_resumes_metadata.json"
CONFIG_JSON_PATH = PROJECT_ROOT / "config.json"

# ---------------------------------------------------------------------------
# Embedding model
# ---------------------------------------------------------------------------
MODEL_NAME = "all-MiniLM-L6-v2"
EMBEDDING_DIM = 384

# ---------------------------------------------------------------------------
# Search defaults
# ---------------------------------------------------------------------------
DEFAULT_TOP_K = 20
MIN_SCORE_THRESHOLD = 0.0

# ---------------------------------------------------------------------------
# Predefined skill suggestions (shown in the sidebar & autocomplete)
# ---------------------------------------------------------------------------
SKILL_SUGGESTIONS = [
    "Python",
    "Machine Learning",
    "Data Science",
    "NLP",
    "SQL",
    "React",
    "Computer Vision",
    "Java",
    "C++",
    "JavaScript",
    "TypeScript",
    "TensorFlow",
    "PyTorch",
    "Deep Learning",
    "Statistics",
    "R",
    "AWS",
    "Docker",
    "Kubernetes",
    "Node.js",
    "HTML/CSS",
    "Git",
    "MongoDB",
    "PostgreSQL",
    "Tableau",
    "Power BI",
    "Spark",
    "Hadoop",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "LLMs",
    "RAG",
    "Transformers",
    "BERT",
    "GPT",
    "Flask",
    "Django",
    "FastAPI",
    "Swift",
    "Kotlin",
    "Rust",
    "Go",
    "Scala",
]

# ---------------------------------------------------------------------------
# UI colour palette (matches the dark-theme mockup)
# ---------------------------------------------------------------------------
COLORS = {
    "bg_dark": "#1a1f2e",
    "sidebar_bg": "#141824",
    "card_bg": "#ffffff",
    "accent_orange": "#f97316",
    "accent_teal": "#2dd4bf",
    "text_primary": "#ffffff",
    "text_secondary": "#94a3b8",
    "text_dark": "#1e293b",
    "border": "#334155",
    "rank_blue": "#38bdf8",
    "score_green": "#22c55e",
    "score_yellow": "#eab308",
    "score_red": "#ef4444",
}
